-- MySQL Script generated by MySQL Workbench
-- Sun Jul 28 16:23:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AsignacionCursos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AsignacionCursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AsignacionCursos` DEFAULT CHARACTER SET utf8 ;
USE `AsignacionCursos` ;

-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Tipo` (
  `iIdTipo` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Estudiantes` (
  `iIdEstudiantes` INT NOT NULL,
  `cNombres` VARCHAR(45) NULL,
  `cApellidos` VARCHAR(45) NULL,
  `iEdad` INT NULL,
  `cDireccion` VARCHAR(45) NULL,
  `cEmail` VARCHAR(45) NULL,
  `cTelefono` VARCHAR(8) NULL,
  `cGenero` VARCHAR(20) NULL,
  PRIMARY KEY (`iIdEstudiantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Facultad` (
  `iIdFacultad` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdFacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Usuarios` (
  `iIdUsuarios` INT NOT NULL,
  `bCorreo` BLOB NULL,
  `bPassword` BLOB NULL,
  `bUsuario` BLOB NULL,
  `iIdEstudiantes` INT NOT NULL,
  `iIdFacultad` INT NOT NULL,
  `iIdTipo` INT NOT NULL,
  PRIMARY KEY (`iIdUsuarios`),
  CONSTRAINT `fk_Usuarios_Alumnos`
    FOREIGN KEY (`iIdEstudiantes`)
    REFERENCES `AsignacionCursos`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuarios_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `AsignacionCursos`.`Facultad` (`iIdFacultad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuarios_Tipo1`
    FOREIGN KEY (`iIdTipo`)
    REFERENCES `AsignacionCursos`.`Tipo` (`iIdTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Carrera` (
  `iIdCarrera` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `iIdFacultad` INT NOT NULL,
  PRIMARY KEY (`iIdCarrera`),
  CONSTRAINT `fk_Carrera_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `AsignacionCursos`.`Facultad` (`iIdFacultad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Salon` (
  `iIdSalon` INT NOT NULL,
  `cNoSalon` VARCHAR(10) NULL,
  PRIMARY KEY (`iIdSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Edificio` (
  `iIdEdificio` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `iIdFacultad` INT NOT NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdEdificio`),
  CONSTRAINT `fk_Edificio_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `AsignacionCursos`.`Facultad` (`iIdFacultad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Edificio_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `AsignacionCursos`.`Salon` (`iIdSalon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Seccion` (
  `iIdSeccion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cCapacidad` VARCHAR(45) NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdSeccion`),
  CONSTRAINT `fk_Seccion_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `AsignacionCursos`.`Salon` (`iIdSalon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Jornada` (
  `iIdJornada` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdJornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Pensum` (
  `iIdPensum` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(10) NULL,
  `cCreditos` VARCHAR(45) NULL,
  `iIdJornada` INT NOT NULL,
  `idCarrera` INT NOT NULL,
  PRIMARY KEY (`iIdPensum`),
  CONSTRAINT `fk_Pensum_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `AsignacionCursos`.`Jornada` (`iIdJornada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pensum_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `AsignacionCursos`.`Carrera` (`iIdCarrera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Curso` (
  `iIdCurso` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cCreditos` INT NULL,
  PRIMARY KEY (`iIdCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`DetallePensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`DetallePensum` (
  `iIdPensum` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdPensum`, `iIdCurso`),
  CONSTRAINT `fk_DetallePensum_Pensum1`
    FOREIGN KEY (`iIdPensum`)
    REFERENCES `AsignacionCursos`.`Pensum` (`iIdPensum`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetallePensum_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `AsignacionCursos`.`Curso` (`iIdCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Semestre` (
  `iIdSemestre` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Horario` (
  `iIdHorario` INT NOT NULL,
  `cDuracion` VARCHAR(45) NULL,
  `cHoraInicio` VARCHAR(45) NULL,
  `cHoraFinal` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Laboratorio` (
  `iIdLaboratorio` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdLaboratorio`),
  CONSTRAINT `fk_Laboratorio_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `AsignacionCursos`.`Salon` (`iIdSalon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Asignacion` (
  `idAsignacion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdEstudiantes` INT NOT NULL,
  `iIdCarrera` INT NOT NULL,
  PRIMARY KEY (`idAsignacion`),
  CONSTRAINT `fk_Asignacion_Alumnos1`
    FOREIGN KEY (`iIdEstudiantes`)
    REFERENCES `AsignacionCursos`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Asignacion_Carrera1`
    FOREIGN KEY (`iIdCarrera`)
    REFERENCES `AsignacionCursos`.`Carrera` (`iIdCarrera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`AsignacionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`AsignacionDetalle` (
  `iIdAsignacionDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdCurso` INT NOT NULL,
  `iIdHorario` INT NOT NULL,
  `iIdSeccion` INT NOT NULL,
  `iIdLaboratorio` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdAsignacion` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionDetalle`),
  CONSTRAINT `fk_AsignacionDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `AsignacionCursos`.`Curso` (`iIdCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionDetalle_Horario1`
    FOREIGN KEY (`iIdHorario`)
    REFERENCES `AsignacionCursos`.`Horario` (`iIdHorario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionDetalle_Seccion1`
    FOREIGN KEY (`iIdSeccion`)
    REFERENCES `AsignacionCursos`.`Seccion` (`iIdSeccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionDetalle_Laboratorio1`
    FOREIGN KEY (`iIdLaboratorio`)
    REFERENCES `AsignacionCursos`.`Laboratorio` (`iIdLaboratorio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionDetalle_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `AsignacionCursos`.`Semestre` (`iIdSemestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionDetalle_Asignacion1`
    FOREIGN KEY (`iIdAsignacion`)
    REFERENCES `AsignacionCursos`.`Asignacion` (`idAsignacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Catedratico` (
  `iIdCatedratico` INT NOT NULL,
  `cNombres` VARCHAR(45) NULL,
  `cApellido` VARCHAR(45) NULL,
  `cEdad` VARCHAR(45) NULL,
  `cDireccion` VARCHAR(45) NULL,
  `cEmail` VARCHAR(45) NULL,
  `cTelefono` VARCHAR(45) NULL,
  `cGenero` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdCatedratico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`AsignacionLista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`AsignacionLista` (
  `iIdAsignacionLista` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `bValidado` TINYINT NULL,
  `iIdJornada` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `iIIdSeccion` INT NOT NULL,
  `iIdCatedratico` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionLista`),
  CONSTRAINT `fk_AsignacionLista_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `AsignacionCursos`.`Jornada` (`iIdJornada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionLista_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `AsignacionCursos`.`Semestre` (`iIdSemestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionLista_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `AsignacionCursos`.`Curso` (`iIdCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionLista_Seccion1`
    FOREIGN KEY (`iIIdSeccion`)
    REFERENCES `AsignacionCursos`.`Seccion` (`iIdSeccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionLista_Catedratico1`
    FOREIGN KEY (`iIdCatedratico`)
    REFERENCES `AsignacionCursos`.`Catedratico` (`iIdCatedratico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`AsignacionListaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`AsignacionListaDetalle` (
  `iIdAsignacionListaDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cStatus` VARCHAR(45) NULL,
  `cNota` VARCHAR(45) NULL,
  `iIdAsignacionLista` INT NOT NULL,
  `iIdAlumnos` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionListaDetalle`),
  CONSTRAINT `fk_AsignacionListaDetalle_AsignacionLista1`
    FOREIGN KEY (`iIdAsignacionLista`)
    REFERENCES `AsignacionCursos`.`AsignacionLista` (`iIdAsignacionLista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionListaDetalle_Alumnos1`
    FOREIGN KEY (`iIdAlumnos`)
    REFERENCES `AsignacionCursos`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`AsignacionCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`AsignacionCurso` (
  `iIdAsignacionCurso` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdCatedratico` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionCurso`),
  CONSTRAINT `fk_AsignacionCurso_Catedratico1`
    FOREIGN KEY (`iIdCatedratico`)
    REFERENCES `AsignacionCursos`.`Catedratico` (`iIdCatedratico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`AsignacionCursoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`AsignacionCursoDetalle` (
  `iIdAsignacionCursoDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iIdAsignacionCurso` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `iIdJornada` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdSeccion` INT NOT NULL,
  `iIdFacultad` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionCursoDetalle`),
  CONSTRAINT `fk_AsignacionCursoDetalle_AsignacionCurso1`
    FOREIGN KEY (`iIdAsignacionCurso`)
    REFERENCES `AsignacionCursos`.`AsignacionCurso` (`iIdAsignacionCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionCursoDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `AsignacionCursos`.`Curso` (`iIdCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionCursoDetalle_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `AsignacionCursos`.`Jornada` (`iIdJornada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionCursoDetalle_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `AsignacionCursos`.`Semestre` (`iIdSemestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionCursoDetalle_Seccion1`
    FOREIGN KEY (`iIdSeccion`)
    REFERENCES `AsignacionCursos`.`Seccion` (`iIdSeccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AsignacionCursoDetalle_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `AsignacionCursos`.`Facultad` (`iIdFacultad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Certificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Certificacion` (
  `iIdCertificacion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdAlumnos` INT NOT NULL,
  PRIMARY KEY (`iIdCertificacion`),
  CONSTRAINT `fk_Certificacion_Alumnos1`
    FOREIGN KEY (`iIdAlumnos`)
    REFERENCES `AsignacionCursos`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`CertificacionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`CertificacionDetalle` (
  `iIdCertificacionDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iNota` INT NULL,
  `iIdCertificacion` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  PRIMARY KEY (`iIdCertificacionDetalle`),
  CONSTRAINT `fk_CertificacionDetalle_Certificacion1`
    FOREIGN KEY (`iIdCertificacion`)
    REFERENCES `AsignacionCursos`.`Certificacion` (`iIdCertificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CertificacionDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `AsignacionCursos`.`Curso` (`iIdCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionCursos`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionCursos`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `fecha_ingreso` VARCHAR(45) NULL,
  `fecho_cierre` VARCHAR(45) NULL,
  `accion` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `mac` VARCHAR(45) NULL,
  `nombrePC` VARCHAR(45) NULL,
  `iIdUsuarios` INT NOT NULL,
  PRIMARY KEY (`idBitacora`),
  CONSTRAINT `fk_Bitacora_Usuarios1`
    FOREIGN KEY (`iIdUsuarios`)
    REFERENCES `AsignacionCursos`.`Usuarios` (`iIdUsuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
