-- MySQL Script generated by MySQL Workbench
-- Sun Jul 28 15:44:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `iIdTipo` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiantes` (
  `iIdEstudiantes` INT NOT NULL,
  `cNombres` VARCHAR(45) NULL,
  `cApellidos` VARCHAR(45) NULL,
  `iEdad` INT NULL,
  `cDireccion` VARCHAR(45) NULL,
  `cEmail` VARCHAR(45) NULL,
  `cTelefono` VARCHAR(8) NULL,
  `cGenero` VARCHAR(20) NULL,
  PRIMARY KEY (`iIdEstudiantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facultad` (
  `iIdFacultad` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdFacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `iIdUsuarios` INT NOT NULL,
  `bCorreo` BLOB NULL,
  `bPassword` BLOB NULL,
  `bUsuario` BLOB NULL,
  `iIdEstudiantes` INT NOT NULL,
  `iIdFacultad` INT NOT NULL,
  `iIdTipo` INT NOT NULL,
  PRIMARY KEY (`iIdUsuarios`),
  INDEX `fk_Usuarios_Alumnos_idx` (`iIdEstudiantes` ASC) VISIBLE,
  INDEX `fk_Usuarios_Facultad1_idx` (`iIdFacultad` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipo1_idx` (`iIdTipo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Alumnos`
    FOREIGN KEY (`iIdEstudiantes`)
    REFERENCES `mydb`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `mydb`.`Facultad` (`iIdFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Tipo1`
    FOREIGN KEY (`iIdTipo`)
    REFERENCES `mydb`.`Tipo` (`iIdTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `iIdCarrera` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `iIdFacultad` INT NOT NULL,
  PRIMARY KEY (`iIdCarrera`),
  INDEX `fk_Carrera_Facultad1_idx` (`iIdFacultad` ASC) VISIBLE,
  CONSTRAINT `fk_Carrera_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `mydb`.`Facultad` (`iIdFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salon` (
  `iIdSalon` INT NOT NULL,
  `cNoSalon` VARCHAR(10) NULL,
  PRIMARY KEY (`iIdSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edificio` (
  `iIdEdificio` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `iIdFacultad` INT NOT NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdEdificio`),
  INDEX `fk_Edificio_Facultad1_idx` (`iIdFacultad` ASC) VISIBLE,
  INDEX `fk_Edificio_Salon1_idx` (`iIdSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Edificio_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `mydb`.`Facultad` (`iIdFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edificio_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `mydb`.`Salon` (`iIdSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seccion` (
  `iIdSeccion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cCapacidad` VARCHAR(45) NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdSeccion`),
  INDEX `fk_Seccion_Salon1_idx` (`iIdSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Seccion_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `mydb`.`Salon` (`iIdSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jornada` (
  `iIdJornada` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdJornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pensum` (
  `iIdPensum` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(10) NULL,
  `cCreditos` VARCHAR(45) NULL,
  `iIdJornada` INT NOT NULL,
  `idCarrera` INT NOT NULL,
  PRIMARY KEY (`iIdPensum`),
  INDEX `fk_Pensum_Jornada1_idx` (`iIdJornada` ASC) VISIBLE,
  INDEX `fk_Pensum_Carrera1_idx` (`idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Pensum_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `mydb`.`Jornada` (`iIdJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pensum_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `mydb`.`Carrera` (`iIdCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `iIdCurso` INT NOT NULL,
  `cNombre` VARCHAR(45) NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cCreditos` INT NULL,
  PRIMARY KEY (`iIdCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetallePensum` (
  `iIdPensum` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  INDEX `fk_DetallePensum_Pensum1_idx` (`iIdPensum` ASC) VISIBLE,
  INDEX `fk_DetallePensum_Curso1_idx` (`iIdCurso` ASC) VISIBLE,
  PRIMARY KEY (`iIdPensum`, `iIdCurso`),
  CONSTRAINT `fk_DetallePensum_Pensum1`
    FOREIGN KEY (`iIdPensum`)
    REFERENCES `mydb`.`Pensum` (`iIdPensum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePensum_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `mydb`.`Curso` (`iIdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Semestre` (
  `iIdSemestre` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `iIdHorario` INT NOT NULL,
  `cDuracion` VARCHAR(45) NULL,
  `cHoraInicio` VARCHAR(45) NULL,
  `cHoraFinal` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio` (
  `iIdLaboratorio` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iIdSalon` INT NOT NULL,
  PRIMARY KEY (`iIdLaboratorio`),
  INDEX `fk_Laboratorio_Salon1_idx` (`iIdSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratorio_Salon1`
    FOREIGN KEY (`iIdSalon`)
    REFERENCES `mydb`.`Salon` (`iIdSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignacion` (
  `idAsignacion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdEstudiantes` INT NOT NULL,
  `iIdCarrera` INT NOT NULL,
  PRIMARY KEY (`idAsignacion`),
  INDEX `fk_Asignacion_Alumnos1_idx` (`iIdEstudiantes` ASC) VISIBLE,
  INDEX `fk_Asignacion_Carrera1_idx` (`iIdCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Asignacion_Alumnos1`
    FOREIGN KEY (`iIdEstudiantes`)
    REFERENCES `mydb`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Carrera1`
    FOREIGN KEY (`iIdCarrera`)
    REFERENCES `mydb`.`Carrera` (`iIdCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignacionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignacionDetalle` (
  `iIdAsignacionDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdCurso` INT NOT NULL,
  `iIdHorario` INT NOT NULL,
  `iIdSeccion` INT NOT NULL,
  `iIdLaboratorio` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdAsignacion` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionDetalle`),
  INDEX `fk_AsignacionDetalle_Curso1_idx` (`iIdCurso` ASC) VISIBLE,
  INDEX `fk_AsignacionDetalle_Horario1_idx` (`iIdHorario` ASC) VISIBLE,
  INDEX `fk_AsignacionDetalle_Seccion1_idx` (`iIdSeccion` ASC) VISIBLE,
  INDEX `fk_AsignacionDetalle_Laboratorio1_idx` (`iIdLaboratorio` ASC) VISIBLE,
  INDEX `fk_AsignacionDetalle_Semestre1_idx` (`iIdSemestre` ASC) VISIBLE,
  INDEX `fk_AsignacionDetalle_Asignacion1_idx` (`iIdAsignacion` ASC) VISIBLE,
  CONSTRAINT `fk_AsignacionDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `mydb`.`Curso` (`iIdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionDetalle_Horario1`
    FOREIGN KEY (`iIdHorario`)
    REFERENCES `mydb`.`Horario` (`iIdHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionDetalle_Seccion1`
    FOREIGN KEY (`iIdSeccion`)
    REFERENCES `mydb`.`Seccion` (`iIdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionDetalle_Laboratorio1`
    FOREIGN KEY (`iIdLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`iIdLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionDetalle_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `mydb`.`Semestre` (`iIdSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionDetalle_Asignacion1`
    FOREIGN KEY (`iIdAsignacion`)
    REFERENCES `mydb`.`Asignacion` (`idAsignacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catedratico` (
  `iIdCatedratico` INT NOT NULL,
  `cNombres` VARCHAR(45) NULL,
  `cApellido` VARCHAR(45) NULL,
  `cEdad` VARCHAR(45) NULL,
  `cDireccion` VARCHAR(45) NULL,
  `cEmail` VARCHAR(45) NULL,
  `cTelefono` VARCHAR(45) NULL,
  `cGenero` VARCHAR(45) NULL,
  PRIMARY KEY (`iIdCatedratico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignacionLista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignacionLista` (
  `iIdAsignacionLista` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `bValidado` TINYINT NULL,
  `iIdJornada` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `iIIdSeccion` INT NOT NULL,
  `iIdCatedratico` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionLista`),
  INDEX `fk_AsignacionLista_Jornada1_idx` (`iIdJornada` ASC) VISIBLE,
  INDEX `fk_AsignacionLista_Semestre1_idx` (`iIdSemestre` ASC) VISIBLE,
  INDEX `fk_AsignacionLista_Curso1_idx` (`iIdCurso` ASC) VISIBLE,
  INDEX `fk_AsignacionLista_Seccion1_idx` (`iIIdSeccion` ASC) VISIBLE,
  INDEX `fk_AsignacionLista_Catedratico1_idx` (`iIdCatedratico` ASC) VISIBLE,
  CONSTRAINT `fk_AsignacionLista_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `mydb`.`Jornada` (`iIdJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionLista_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `mydb`.`Semestre` (`iIdSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionLista_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `mydb`.`Curso` (`iIdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionLista_Seccion1`
    FOREIGN KEY (`iIIdSeccion`)
    REFERENCES `mydb`.`Seccion` (`iIdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionLista_Catedratico1`
    FOREIGN KEY (`iIdCatedratico`)
    REFERENCES `mydb`.`Catedratico` (`iIdCatedratico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignacionListaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignacionListaDetalle` (
  `iIdAsignacionListaDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cStatus` VARCHAR(45) NULL,
  `cNota` VARCHAR(45) NULL,
  `iIdAsignacionLista` INT NOT NULL,
  `iIdAlumnos` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionListaDetalle`),
  INDEX `fk_AsignacionListaDetalle_AsignacionLista1_idx` (`iIdAsignacionLista` ASC) VISIBLE,
  INDEX `fk_AsignacionListaDetalle_Alumnos1_idx` (`iIdAlumnos` ASC) VISIBLE,
  CONSTRAINT `fk_AsignacionListaDetalle_AsignacionLista1`
    FOREIGN KEY (`iIdAsignacionLista`)
    REFERENCES `mydb`.`AsignacionLista` (`iIdAsignacionLista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionListaDetalle_Alumnos1`
    FOREIGN KEY (`iIdAlumnos`)
    REFERENCES `mydb`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignacionCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignacionCurso` (
  `iIdAsignacionCurso` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdCatedratico` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionCurso`),
  INDEX `fk_AsignacionCurso_Catedratico1_idx` (`iIdCatedratico` ASC) VISIBLE,
  CONSTRAINT `fk_AsignacionCurso_Catedratico1`
    FOREIGN KEY (`iIdCatedratico`)
    REFERENCES `mydb`.`Catedratico` (`iIdCatedratico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignacionCursoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignacionCursoDetalle` (
  `iIdAsignacionCursoDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iIdAsignacionCurso` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  `iIdJornada` INT NOT NULL,
  `iIdSemestre` INT NOT NULL,
  `iIdSeccion` INT NOT NULL,
  `iIdFacultad` INT NOT NULL,
  PRIMARY KEY (`iIdAsignacionCursoDetalle`),
  INDEX `fk_AsignacionCursoDetalle_AsignacionCurso1_idx` (`iIdAsignacionCurso` ASC) VISIBLE,
  INDEX `fk_AsignacionCursoDetalle_Curso1_idx` (`iIdCurso` ASC) VISIBLE,
  INDEX `fk_AsignacionCursoDetalle_Jornada1_idx` (`iIdJornada` ASC) VISIBLE,
  INDEX `fk_AsignacionCursoDetalle_Semestre1_idx` (`iIdSemestre` ASC) VISIBLE,
  INDEX `fk_AsignacionCursoDetalle_Seccion1_idx` (`iIdSeccion` ASC) VISIBLE,
  INDEX `fk_AsignacionCursoDetalle_Facultad1_idx` (`iIdFacultad` ASC) VISIBLE,
  CONSTRAINT `fk_AsignacionCursoDetalle_AsignacionCurso1`
    FOREIGN KEY (`iIdAsignacionCurso`)
    REFERENCES `mydb`.`AsignacionCurso` (`iIdAsignacionCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionCursoDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `mydb`.`Curso` (`iIdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionCursoDetalle_Jornada1`
    FOREIGN KEY (`iIdJornada`)
    REFERENCES `mydb`.`Jornada` (`iIdJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionCursoDetalle_Semestre1`
    FOREIGN KEY (`iIdSemestre`)
    REFERENCES `mydb`.`Semestre` (`iIdSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionCursoDetalle_Seccion1`
    FOREIGN KEY (`iIdSeccion`)
    REFERENCES `mydb`.`Seccion` (`iIdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionCursoDetalle_Facultad1`
    FOREIGN KEY (`iIdFacultad`)
    REFERENCES `mydb`.`Facultad` (`iIdFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificacion` (
  `iIdCertificacion` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `cFecha` VARCHAR(45) NULL,
  `iIdAlumnos` INT NOT NULL,
  PRIMARY KEY (`iIdCertificacion`),
  INDEX `fk_Certificacion_Alumnos1_idx` (`iIdAlumnos` ASC) VISIBLE,
  CONSTRAINT `fk_Certificacion_Alumnos1`
    FOREIGN KEY (`iIdAlumnos`)
    REFERENCES `mydb`.`Estudiantes` (`iIdEstudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CertificacionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CertificacionDetalle` (
  `iIdCertificacionDetalle` INT NOT NULL,
  `cDescripcion` VARCHAR(45) NULL,
  `iNota` INT NULL,
  `iIdCertificacion` INT NOT NULL,
  `iIdCurso` INT NOT NULL,
  PRIMARY KEY (`iIdCertificacionDetalle`),
  INDEX `fk_CertificacionDetalle_Certificacion1_idx` (`iIdCertificacion` ASC) VISIBLE,
  INDEX `fk_CertificacionDetalle_Curso1_idx` (`iIdCurso` ASC) VISIBLE,
  CONSTRAINT `fk_CertificacionDetalle_Certificacion1`
    FOREIGN KEY (`iIdCertificacion`)
    REFERENCES `mydb`.`Certificacion` (`iIdCertificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CertificacionDetalle_Curso1`
    FOREIGN KEY (`iIdCurso`)
    REFERENCES `mydb`.`Curso` (`iIdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `fecha_ingreso` VARCHAR(45) NULL,
  `fecho_cierre` VARCHAR(45) NULL,
  `accion` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `mac` VARCHAR(45) NULL,
  `nombrePC` VARCHAR(45) NULL,
  `iIdUsuarios` INT NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `fk_Bitacora_Usuarios1_idx` (`iIdUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Bitacora_Usuarios1`
    FOREIGN KEY (`iIdUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`iIdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
